args <- commandArgs(trailingOnly = TRUE)
if (length(args) != 3) stop("Usage: Rscript run_limma.R expression_matrix.csv sample_metadata.csv output_dir")
expr_file <- args[[1]]
meta_file <- args[[2]]
out_dir <- args[[3]]
dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)
if (!requireNamespace("limma", quietly = TRUE)) stop("Bioconductor package 'limma' is required. Install it in the selected R environment.")
expr <- read.csv(expr_file, check.names = FALSE, stringsAsFactors = FALSE)
meta <- read.csv(meta_file, check.names = FALSE, stringsAsFactors = FALSE)
if (!all(c("sample_id", "group") %in% names(meta))) stop("Metadata requires columns: sample_id, group; include dataset_id for provenance.")
if (!"gene" %in% names(expr)) stop("Expression matrix requires a 'gene' column and one column per sample.")
if (anyDuplicated(meta$sample_id)) stop("Duplicate sample_id in metadata.")
if (length(unique(meta$group)) != 2) stop("This implementation supports exactly two groups per contrast.")
if (!all(meta$sample_id %in% names(expr))) stop("Not all metadata sample_id values are columns in the expression matrix.")
mat <- as.matrix(expr[, meta$sample_id, drop = FALSE])
suppressWarnings(storage.mode(mat) <- "numeric")
if (anyNA(mat) || any(!is.finite(mat))) stop("Expression values must be finite numeric values without missing entries.")
if (any(mat < 0)) stop("Negative expression values detected; expected normalized log-scale expression, not raw counts.")
rownames(mat) <- make.unique(as.character(expr$gene))
meta$group <- factor(meta$group, levels = unique(meta$group))
design <- model.matrix(~0 + group, data = meta)
colnames(design) <- make.names(levels(meta$group))
contrast <- paste0(colnames(design)[2], "-", colnames(design)[1])
cont <- limma::makeContrasts(contrasts = contrast, levels = design)
fit <- limma::lmFit(mat, design)
fit <- limma::contrasts.fit(fit, cont)
fit <- limma::eBayes(fit)
out <- limma::topTable(fit, number = Inf, sort.by = "P")
out$gene <- rownames(out)
names(out)[names(out) == "P.Value"] <- "p_value"
names(out)[names(out) == "adj.P.Val"] <- "adjusted_p_value"
write.csv(out, file.path(out_dir, "limma_DEG_results.csv"), row.names = FALSE)
write.csv(data.frame(sample_id = meta$sample_id, group = meta$group), file.path(out_dir, "sample_group_manifest.csv"), row.names = FALSE)
writeLines(c("Analysis: limma linear model with empirical Bayes moderation", paste0("Contrast: ", contrast), "Input expectation: normalized log-scale expression matrix (not raw counts)", paste0("Samples: ", nrow(meta)), paste0("Genes: ", nrow(mat)), paste0("limma version: ", as.character(utils::packageVersion("limma")))), file.path(out_dir, "analysis_method.txt"))
